"""create tables

Revision ID: 02c1e2e4223f
Revises: 
Create Date: 2023-05-11 01:00:22.979776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02c1e2e4223f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "data_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "fact_plan_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "q_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "test_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("data", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("data_type_id", sa.Integer(), nullable=False),
        sa.Column("q_type_id", sa.Integer(), nullable=False),
        sa.Column("fact_plan_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["data_type_id"],
            ["data_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fact_plan_type_id"],
            ["fact_plan_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["q_type_id"],
            ["q_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_table")
    op.drop_table("q_type")
    op.drop_table("fact_plan_type")
    op.drop_table("data_type")
    op.drop_table("company")
    # ### end Alembic commands ###
